-- phpMyAdmin SQL Dump
-- version 5.1.3
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: May 04, 2022 at 12:36 AM
-- Server version: 10.4.21-MariaDB
-- PHP Version: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `chatbot`
--

-- --------------------------------------------------------

--
-- Table structure for table `chatbot`
--

CREATE TABLE `chatbot` (
  `id` int(100) NOT NULL,
  `user_query` varchar(7000) NOT NULL,
  `bot_reply` varchar(7000) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `chatbot`
--

INSERT INTO `chatbot` (`id`, `user_query`, `bot_reply`) VALUES
(1, 'Hi|hello|hey|hi! |hy', 'Hello there! How can I help you? You can ask for information about any historical place. \r\n'),
(2, 'How are you|How are you today?|how you doing|how you been', 'I am doing great, what would you like to know about ? '),
(3, 'Who are you| who are you ?| What are you | what do you do ', 'I am a Simple Chatbot, my name is INFO BOT. I can provide you with information you would like to know about famous historical places. You can type in something like \"what places\" , \"which places\" to know what kind of historical places I can provide information about. '),
(4, 'How can you help me| what can you do| how are you useful| what is your job| Can you help me | help me | help', 'I am a Simple Chatbot, my name is INFO BOT. I can provide you with information you would like to know about famous historical places. You can type in something like \"what places\" , \"which places\" to know what kind of historical places I can provide information about. '),
(5, 'What all the historical places you can give information about| what historical places| which places | what part of world ', 'I can provide information about famous historical places like wonders of the world, famous historical buildings, famous historical tourists places and famous historical museums. You can type in something like \"what places\" , \"which places\".'),
(6, 'What kind of information| what information| which information| information ?|whose information | what kind of information do you provide', 'I provide Information like why the historical places are famous, their greatness, and some reference links to check more information about the historical places. You can type in something like \"what places\" , \"which places\"'),
(7, 'what places? | what places |what kind of places| which places | what places can you give info about | about which places you can give info| what other places | what else | ', 'I can provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information about. '),
(8, 'Wonders| wonders of the world | I Would like to know about wonders |I Would like to know about wonders of the world | List of wonders | wonders List ', 'Here is the list of Wonders of the World. Which one would you like to know?\r\n1. Great Wall of China\r\n2. Petra\r\n3. The Taj Mehal\r\n4. Machu Picchu\r\n5. Christ the Redeemer\r\n6. The Chichen Itza\r\n7. The Colosseum . \r\n\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(9, 'Great Wall of China | option 1| great of wall of china| wall of china | china wall| great wall  ', 'The great china wall is located in Beijing, China. It is a powerful symbol of Chinese civilization\'s enduring strength. It is the longest wall in the world. If you would like to know more about this wonder please click here: <a href=\'https://www.nationalgeographic.org/encyclopedia/great-wall-china\'/> Great Wall of China. </a>\r\n\r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(10, ' Petra |  about petra', 'Petra is located in Ma\'an GOvernorate, Jordan. Famous for its rock-cut architecture and water conduit system. It is popularly known as Rose Red City. If you would like to know more about this wonder please click here: <a href=\'https://www.nationalgeographic.com/history/article/lost-city-petra\'/> Petra </a>\r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(11, 'The Taj Mehal| taj | mehal | taj mehal ', 'Taj Mehal is located in Mausoleum in Agra, India. It is a symmetry and harmonious blending of various elements. Arguably the greatest gesture of love ever made by man. If you would like to know more about this wonder please click here: <a href=\'https://whc.unesco.org/en/list/252/\'/> The Taj Mehal </a>\r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(12, ' Machu Picchu | machu | picchu ', 'Machu Picchu is located in Eastern Cordillera of southern Peru. It is famous because of its intricate system of Inca ruins. It is an Urban creation of the Inca Empire. If you would like to know more about this wonder please click here: <a href=\'https://www.nationalgeographic.com/history/article/machu-picchu-mystery\'/> Machu Picchu </a>\r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(13, ' Christ the Redeemer  | christ| redeemer ', 'Christ the Redeemer is located in  Rio de Janeiro, Brazil, Corcovado. It is a symbolic protector of people. It is the greatest feat of Brazilian engineering. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/topic/Christ-the-Redeemer\'/> Christ the Redeemer </a>\r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(14, 'The Chichen Itza | The chichen | chichen | chichen itza| itza', 'The Chichen Itza is located in Yucatan, Mexico. It\'s large concentration of culturally-significant. It is popularly known as one of the Ancient manmade wonders. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/place/Chichen-Itza\'/> The Chichen Itza </a>. \r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(15, 'The Colosseum | colosseum ', 'The Colosseum is located in Rome, Italy. It is famous for hosting events like gladiatorial games. It is also a Symbol of the imperial greatness. If you would like to know more about this wonder please click here: <a href=\'https://www.smithsonianmag.com/history/secrets-of-the-colosseum-75827047/\'/> The Colosseum </a >\r\nHere is the list of Wonders of the World. Which one would you like to know? 1. Great Wall of China 2. Petra 3. The Taj Mehal 4. Machu Picchu 5. Christ the Redeemer 6. The Chichen Itza 7. The Colosseum. \r\n\r\nPlease type in the name of the place to know information about it.\r\n\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(16, 'Famous Historical Buildings| Buildings | historical buildings', 'Here are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(17, 'Colosseum ', 'Colosseum is located in Rome. It is famously used for gladiatorial combat.It is one of the largest amphitheater in the world. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/topic/Colosseum\'/> Colosseum  </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(18, 'Westmininster Abbey | westminister | abbey ', 'Westmininster Abbey is located in London. This serves as a site for royal coronations and burials. Westminster Abbey has famously been the location for 17 royal weddings. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/topic/Westminster-Abbey\'/> Westmininster Abbey </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(19, 'The white House| white | house | white house ', 'The white House is located in United States of America. It is the headquarters of the president\'s principal staff members. It is the only private residence of a head of state that is open to the public, free of charge. If you would like to know more about this wonder please click here: <a href=\'https://www.whitehouse.gov/about-the-white-house/the-grounds/the-white-house/\'/> The white House </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(20, 'Leaning Tower of Pisa| pisa| tower os pisa | leaning tower| leaning of pisa', 'Leaning Tower of Pisa is located in Pisa. It is famous for the settling of its foundations. The tower has leaned in multiple directions. If you would like to know more about this wonder please click here: <a href=\'https://www.towerofpisa.org/leaning-tower-of-pisa-facts/\'/> Leaning Tower of Pisa </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(21, 'The blue Mosque| mosque| blue mosque| blue | the blue', 'The blue Mosque is located in Instanbul. It is famous due to the blue color that dominates the interior of the mosque. It is huge and it is 6 minarets.  If you would like to know more about this wonder please click here: <a href=\'https://smarthistory.org/the-blue-mosque-sultan-ahmet-camii/#:~:text=The%20Sultan%20Ahmet%20Mosque%2C%20popularly,and%20six%20slender%20soaring%20minarets.\'/> The blue Mosque </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(22, 'Eiffel Tower | tower | eiffel', 'Eiffel Tower is located in Paris. It is symbolized French know-how and industrial genius. It impressed the entire world by its stature and daring design. If you would like to know more about this wonder please click here: <a href=\'https://www.toureiffel.paris/en/the-monument/history\'/> Eiffel Tower </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(23, 'Alhambra ', 'Alhambra is located in Granada. It provides a breathtaking view of the entire city of Granada. It has sophisticated planning, complex decorative programs, and its many enchanting gardens and fountains. If you would like to know more about this wonder please click here: <a href=\'https://www.khanacademy.org/humanities/ap-art-history/early-europe-and-colonial-americas/ap-art-islamic-world-medieval/a/the-alhambra\'/> Alhambra </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(24, 'The Alamo | alamo', 'The Alamo is located in San Antonio. It is an enduring symbol of their resistance to oppression and their struggle for independence. It had one of the first hospitals in Texas. If you would like to know more about this wonder please click here: <a href=\'https://www.history.com/topics/mexico/alamo\'/> The Alamo </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(25, 'Porta Nigra | nigra | porta ', 'Porta Nigra is located in Trier. It is the largest Roman city gate north of the Alps. It has a burial place in the 11th century and later as a collegiate church, i.e. the sacral building of a religious institution. If you would like to know more about this wonder please click here: <a href=\'https://www.livius.org/articles/place/augusta-treverorum-trier/trier-photos/trier-porta-nigra/\'/> Porta Nigra </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(26, 'Bolshoi Theatre| Theatre | Bolshoi', 'Bolshoi Theatre is located in Moscow. It is among the oldest and best known ballet and opera companies in the world. Also, it is among the oldest and best known ballet and opera companies in the world. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/topic/Bolshoi-Theatre\'/> Bolshoi Theatre </a>\r\nHere are some of the Famous Historical Buildings in the world. \r\n1. Colosseum \r\n2. Westmininster Abbey\r\n3. The white House\r\n4. Leaning Tower of Pisa\r\n5. The blue Mosque\r\n6. Eiffel Tower\r\n7. Alhambra \r\n8. The Alamo\r\n9. Porta Nigra\r\n10. Bolshoi Theatre\r\nPlease type in the name of the place to know information about it. \r\nOR\r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(27, 'Famous Historical Museums | Museums | Historical Museums | Famous Museums\r\n', 'Here are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(28, 'Louvre', 'Louvre is located in Paris. It has artifacts representative of 11,000 years of human civilization and culture. It is one of the richest places in the world. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/topic/Louvre-Museum\'/> Louvre </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(29, 'National Museum of China | national museum | museum of china', 'National Museum of China is located in Beijing. It is evolutionary culture and advanced socialist culture. It is collection of Qing era (1644 to 1912) imperial treasure and ancient porcelain and cloisonne ware. If you would like to know more about this wonder please click here: <a href=\'https://www.researchgate.net/publication/327890322_The_National_Museum_of_China\'/> National Museum of China </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(30, 'Nanjing Museum| Nanjing', 'Nanjing Museum is located in Nanjing. which is among the largest museums in the world. The museum\'s enormous collections of Ming and Qing imperial porcelain. If you would like to know more about this wonder please click here: <a href=\'https://siarchives.si.edu/history/national-museum-natural-history\'/> Nanjing Museum </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(31, 'Tate Modern | tate | modern', 'Tate Modern is located in London. It is one of the world\'s pre-eminent contemporary art galleries. It is Turbine Hall installations draw thousands to the South Bank. If you would like to know more about this wonder please click here: <a href=\'https://www.theartnewspaper.com/keywords/tate-modern\'/> Tate Modern </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(32, 'Shanghai Science and technology Museum | shanghai museum | Science Museum |technology Museum| Science and technology Museum', 'Shanghai Science and technology Museum is located in Shanghai. It is one of the world\'s pre-eminent contemporary art galleries. It is the largest collection of rare cultural pieces. If you would like to know more about this wonder please click here: <a href=\'https://www.nature.com/articles/d41586-022-01052-z\'/> Shanghai Science and technology Museum </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(33, 'vatican Museums| vatican | vatican Museum', 'Vatican Museum is located in Vatican City. It is host to the most important and largest art collection in the world. It is the centre of authority over the Roman Catholic Church. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/place/Vatican-City\'/> Vatican Museum </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(34, 'The British museum | British |british museum', 'The British museum is located in London. The first national public museum of the world. It is the centre of authority over the Roman Catholic Church. If you would like to know more about this wonder please click here: <a href=\'https://www.britishmuseum.org/about-us/british-museum-story\'/> The British museum </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(35, 'The metropolitan Museum of Art | museum of art | metropolitan Museum | metropolitan art | art museum ', 'The metropolitan Museum of Art is located in New York. It is a home of renowned paintings. It is a home of renowned paintings. If you would like to know more about this wonder please click here: <a href=\'https://www.metmuseum.org/\'/> The metropolitan Museum of Art </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(36, 'The national Gallery  | national gallery | gallery', 'The national gallery is located in Trafalgar Square. It serves as a center of visual art, education, and culture. It is including the only painting by Leonardo da Vinci in the Americas and the largest mobile created by Alexander Calder. If you would like to know more about this wonder please click here: <a href=\'https://www.nationalgallery.org.uk/\'/> The national Gallery </a>\r\nHere are some of the Famous Historical Museums in the world. \r\n1. Louvre\r\n2. National Museum of China\r\n3. Nanjing Museum\r\n4. Tate Modern\r\n5. Shanghai Science and technology Museum\r\n6. vatican Museums\r\n7. The British museum\r\n8. The metropolitan Museum of Art\r\n9. The national Gallery \r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(37, 'Famous Historical Tourist Places | tourist places | Historical Tourist Places| Famous Historical Places | Famous Historical', 'Here are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(38, 'Stonehedge', 'Stonehedge is located in Wiltshire, United Kingdom. It is the most architecturally sophisticated prehistoric stone circle in the world. It is perhaps the world\'s most famous prehistoric monument. If you would like to know more about this wonder please click here: <a href=\'https://www.smithsonianmag.com/history/new-light-on-stonehenge-11706891/\'/> Stonehedge </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(39, 'Great Pyramid of Giza| giza | pyramid of giza | great pyramid', 'Great Pyramid of Giza is located in Cairo, Egypt. It is the largest and most recognizable pyramid structures in the world. It is built to honor certain Pharaohs of the fourth ruling dynasty of Egypt during a period known as the Old Kingdom. If you would like to know more about this wonder please click here: <a href=\'https://www.britannica.com/topic/Pyramids-of-Giza\'/> Great Pyramid of Giza </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(40, 'Easter Island | island | easter ', 'Easter Island is located in Chile. It is stone statues of human figures, known as moai. The island is known to its inhabitants as Rapa Nui. If you would like to know more about this wonder please click here: <a href=\'https://www.khanacademy.org/humanities/ap-art-history/pacific-apah/polynesia-apah/a/easter-island-moai#:~:text=Easter%20Island%20is%20famous%20for,half%20of%20the%20seventeenth%20century.\'/> Easter Island </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(41, 'Christ the Redeemer (statue)| statue | Redeemer statue | Christ the Redeemer', 'Christ the Redeemer is located in Rio, Brazil. It is a symbolic protector of people. It is receives around 2.5 million visitors a year. If you would like to know more about this wonder please click here: <a href=\'https://www.historyhit.com/locations/christ-the-redeemer/\'/> Christ the Redeemer (statue) </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(42, 'Parthenon', 'Parthenon is located in Athens,Greece. It is the symbol of Athens democracy. It is also symbol of the power, wealth and elevated culture of Athens. If you would like to know more about this wonder please click here: <a href=\'https://www.smithsonianmag.com/history/unlocking-mysteries-of-the-parthenon-16621015/\'/> Parthenon </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(43, 'Angkor Wat | wat | angkor', 'Angkor Wat is located in Siem Reap, Cambodia. It is the most famous ancient temple site in Cambodia. It is An Architectural Masterpiece. If you would like to know more about this wonder please click here: <a href=\'https://www.lonelyplanet.com/articles/cambodia-famous-temple-angkor-wat-info\'/> Angkor Wat </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(44, 'Borobudur', 'Borobudur is located in Yogyakarta, Indonesia. It is the largest Buddhist temple in the world. It is a Buddhist commemorative mound usually containing holy relics. If you would like to know more about this wonder please click here: <a href=\'https://www.khanacademy.org/humanities/ap-art-history/south-east-se-asia/indonesia-art/a/borobudur\'/> Borobudur </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(45, 'The Ellora Caves | ellora caves | ellora | caves ', 'The Ellora Caves is located in Aurangabad, India. It is the largest single monolithic excavation in the world, the great Kailasa. But it\'s shining glory is the Kailasa temple (cave 16); the world\'s largest monolithic sculpture, carved out by 7000 labourers over a period of 150 years. If you would like to know more about this wonder please click here: <a href=\'https://whc.unesco.org/en/list/243/\'/> The Ellora Caves </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.'),
(46, 'Göbekli Tepe | Tepe | Göbekli | gobekli', 'Göbekl Tepe is located in Southeastern Anatolia Region of Turkey. It is one of the most important archaeological sites in the world. If you would like to know more about this wonder please click here: <a href=\'https://www.smithsonianmag.com/history/gobekli-tepe-the-worlds-first-temple-83613665/\'/> Göbekli Tepe </a>\r\nHere are some of the Famous Historical Tourist Places in the world. \r\n1. Stonehedge\r\n2. Great Pyramid of Giza\r\n3. Easter Island\r\n4. Christ the Redeemer (statue)\r\n5. Parthenon\r\n6. Angkor Wat\r\n7. Borobudur\r\n8. The Ellora Caves\r\n9. Göbekli Tepe\r\nPlease type in the name of the place to know information about it. \r\nOR \r\nIf you want to know about some other places, I can also provide information about: \r\nWonders of the world, Famous Historical Buildings, Famous Historical Museums and Famous Historical Tourist Places \r\nPlease select one of the above, I can give a list of places that you can get information.\r\n'),
(47, 'Thank you for info | thanks | Thank you | You are so helpful | Thanks for the help |', 'You are welcome, Have a good one !!!!');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `chatbot`
--
ALTER TABLE `chatbot`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `chatbot`
--
ALTER TABLE `chatbot`
  MODIFY `id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=48;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
